### ISSUE TITLE
Cut Copy Paste

### ISSUE THREAD

**Issue by prakash2033** [BrodieRobertson/st-fork#1]
What shortcut to use for cut copy paste in st terminal?

For e.g. I want to select the command output or anything which can be selected in st terminal.

please respond.

**Comment by prakash2033** [comment]
Ctrl Shift c works for copy
Ctrl Shift y Paste from primary selection (mouse middle click)
or Ctrl Shift v Paste from clipboard

**Comment by ankitjosh78** [comment]
> Ctrl Shift c works for copy
> Ctrl Shift y Paste from primary selection (mouse middle click)
> or Ctrl Shift v Paste from clipboard

Hey, I tried this but the shortcuts doesn't seem to work on my system.
